modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="essai"
version="1.0.0"
displayName="essai1"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Utilisateur, MCreator"

[[dependencies.essai]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




